import PDFDocument from 'pdfkit';

// The standard PDF fonts only cover Latin-1, so ₹ prints as "INR" and other
// symbols are replaced rather than rendered as garbage.
const clean = (value) => String(value ?? '')
  .replace(/₹\s?/g, 'INR ')
  .replace(/→/g, '->')
  .replace(/[^\x20-\x7E -ÿ–—‘’“”•…]/g, '')
  .trim();
const money = (n) => `INR ${Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const istTime = (iso) => {
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? '' : `${date.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', dateStyle: 'medium', timeStyle: 'short' })} IST`;
};

const INK = '#0f172a', MUTED = '#64748b', BRAND = '#0e7490', RULE = '#e2e8f0';

function row(doc, label, value, y, { bold = false, x = 50, width = 495 } = {}) {
  doc.font('Helvetica').fontSize(10).fillColor(MUTED).text(label, x, y, { width: width / 2 });
  doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fillColor(INK).text(clean(value) || '-', x + width / 2, y, { width: width / 2, align: 'right' });
  return y + 18;
}

export function renderInvoicePdf(invoice, booking = null) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, info: { Title: `TravoAI receipt ${invoice.invoice_no}`, Author: 'TravoAI' } });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.rect(0, 0, doc.page.width, 96).fill('#ecfeff');
    doc.font('Helvetica-Bold').fontSize(24).fillColor(BRAND).text('TravoAI', 50, 34);
    doc.font('Helvetica').fontSize(9).fillColor(MUTED).text('AI travel planner', 50, 62);
    doc.font('Helvetica-Bold').fontSize(14).fillColor(INK).text('PAYMENT RECEIPT', 300, 34, { width: 245, align: 'right' });
    doc.font('Helvetica').fontSize(9).fillColor(MUTED)
      .text(clean(invoice.invoice_no), 300, 54, { width: 245, align: 'right' })
      .text(istTime(invoice.issued_at), 300, 67, { width: 245, align: 'right' });

    let y = 118;
    if (invoice.test_mode) {
      doc.roundedRect(50, y, 495, 34, 6).fill('#fef3c7');
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#92400e')
        .text('TEST MODE  -  Razorpay test payment. No real money was charged.', 62, y + 12, { width: 471 });
      y += 50;
    }

    doc.font('Helvetica-Bold').fontSize(11).fillColor(INK).text('Billed to', 50, y);
    doc.font('Helvetica').fontSize(10).fillColor(INK).text(clean(invoice.customer) || 'Guest', 50, y + 16);
    doc.font('Helvetica-Bold').fontSize(11).text('Paid via', 300, y, { width: 245, align: 'right' });
    doc.font('Helvetica').fontSize(10).text(clean(invoice.gateway), 300, y + 16, { width: 245, align: 'right' });
    y += 48;

    if (booking) {
      doc.moveTo(50, y).lineTo(545, y).strokeColor(RULE).stroke();
      y += 12;
      doc.font('Helvetica-Bold').fontSize(11).fillColor(INK).text('Booking', 50, y);
      y += 20;
      y = row(doc, 'Item', booking.item_name || booking.name, y);
      y = row(doc, 'Destination', booking.destination || booking.location, y);
      y = row(doc, 'Duration', booking.details, y);
      y = row(doc, 'Guests', booking.guests, y);
      y = row(doc, 'Booking ID', booking.booking_id, y);
      y = row(doc, 'Status', booking.status === 'cancelled' ? 'Cancelled' : `Paid - supplier confirmation ${booking.supplier_status || 'pending'}`, y);
      y += 6;
    }

    doc.moveTo(50, y).lineTo(545, y).strokeColor(RULE).stroke();
    y += 12;
    doc.font('Helvetica-Bold').fontSize(10).fillColor(MUTED).text('DESCRIPTION', 50, y).text('AMOUNT', 300, y, { width: 245, align: 'right' });
    y += 18;
    for (const item of invoice.line_items || []) {
      doc.font('Helvetica').fontSize(10).fillColor(INK).text(clean(item.label), 50, y, { width: 330 });
      doc.text(money(item.amount), 300, y, { width: 245, align: 'right' });
      y = Math.max(doc.y, y + 16) + 4;
    }
    doc.moveTo(50, y).lineTo(545, y).strokeColor(RULE).stroke();
    y += 10;
    y = row(doc, 'Total', money(invoice.nominal_amount), y, { bold: true });
    y = row(doc, `Charged via ${clean(invoice.gateway)}`, money(invoice.amount_charged), y);
    if (invoice.balance_amount > 0) y = row(doc, 'Balance (not collected online)', money(invoice.balance_amount), y);
    y += 8;

    doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text('Payment reference', 50, y);
    y += 16;
    if (invoice.payment_id) y = row(doc, 'Payment ID', invoice.payment_id, y);
    y = row(doc, 'Order ID', invoice.order_id, y);

    doc.font('Helvetica').fontSize(8.5).fillColor(MUTED)
      .text(clean(invoice.settlement_note), 50, y + 16, { width: 495 })
      .text(`Generated by TravoAI on ${istTime(new Date().toISOString())}.`, 50, 780, { width: 495, align: 'center' });
    doc.end();
  });
}
